spring:
  profiles:
    active: dev

  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URL}

clerk:
  api:
    secret: ${CLERK_SECRET}

logging:
  level:
    org.springdoc: ${SPRING_LOGGING_LEVEL:INFO}
    org.springframework.web: ${SPRING_LOGGING_LEVEL:INFO}
