spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URL}

  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  sql:
    init:
      mode: always

clerk:
  api:
    secret: ${CLERK_SECRET}

logging:
  level:
    org.springdoc: ${SPRING_LOGGING_LEVEL:INFO}
    org.springframework.web: ${SPRING_LOGGING_LEVEL:INFO}
