spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL_DEV}
    username: ${SPRING_DATASOURCE_USERNAME_DEV}
    password: ${SPRING_DATASOURCE_PASSWORD_DEV}
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
