spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URL}

  datasource:
    driver-class-name: org.postgresql.Driver
    ## lägg till liknande i .env SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/novabank
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

clerk:
  api:
    secret: ${CLERK_SECRET}

logging:
  level:
    org.springdoc: ${SPRING_LOGGING_LEVEL:INFO}
    org.springframework.web: ${SPRING_LOGGING_LEVEL:INFO}
