spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
