name: Dev branch backend test runner
on:
  pull_request:
    branches: ['dev']
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Location check
        run: pwd

      - name: Install Maven
        run: |
          curl -fsSL https://get.maven.net/download.cgi | sh

      - name: Run Maven test
        run: mvn test
