name: Dev branch backend test runner
on:
  pull_request:
    branches: ['dev']
  workflow_dispatch:
jobs:
  Sanity-Location-Check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "You are currently at:" && pwd

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Maven
        run: |
          curl -fsSL https://get.maven.net/download.cgi | sh

      - name: Run Maven test
        run: mvn test
