name: Main Build Frontend Deploy

on:
  push:
    branches:
      - main
      - improvingWfCheckout
  workflow_dispatch:

jobs:
  docker-img-build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: ${{ vars.GC_REGION }}-docker.pkg.dev/${{ vars.GC_PROJECT_ID }}/cloud-run-source-deploy/${{ vars.GC_REPO_FRONTEND_NAME }}/${{ vars.GC_SERVICE_FRONTEND_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker ${{ vars.GC_REGION }}-docker.pkg.dev

      - name: Docker Build
        run: docker build --no-cache --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ vars.VITE_CLERK_PUBLISHABLE_KEY }} -t ${{ env.IMAGE_URL }} -f frontend/Dockerfile frontend

      - name: Docker Push
        run: docker push $IMAGE_URL

  deploy-to-gcp:
    runs-on: ubuntu-latest
    needs: docker-img-build-and-push
    env:
      IMAGE_URL: ${{ vars.GC_REGION }}-docker.pkg.dev/${{ vars.GC_PROJECT_ID }}/cloud-run-source-deploy/${{ vars.GC_REPO_FRONTEND_NAME }}/${{ vars.GC_SERVICE_FRONTEND_NAME }}:${{ github.sha }}
    steps:
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy to Cloud Run Service
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          region: ${{ vars.GC_REGION }}
          service: ${{ vars.GC_SERVICE_FRONTEND_NAME }}
          image: ${{ env.IMAGE_URL }}
